In [1]:
import pandas as pd
df = pd.read_csv("titanic.csv")

In [2]:
df.describe()

,PassengerId,Pclass,Age,SibSp,Parch,Fare,Survived
count,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000,891.000000
mean,446.000000,2.308642,29.699118,0.523008,0.381594,32.204208,0.383838
std,257.353842,0.836071,14.526497,1.102743,0.806057,49.693429,0.486592
min,1.000000,1.000000,0.420000,0.000000,0.000000,0.000000,0.000000
25%,223.500000,2.000000,20.125000,0.000000,0.000000,7.910400,0.000000
50%,446.000000,3.000000,28.000000,0.000000,0.000000,14.454200,0.000000
75%,668.500000,3.000000,38.000000,1.000000,0.000000,31.000000,1.000000
max,891.000000,3.000000,80.000000,8.000000,6.000000,512.329200,1.000000

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Name         891 non-null    str
 2   Pclass       891 non-null    int64
 3   Sex          891 non-null    str
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64
 6   Parch        891 non-null    int64
 7   Ticket       891 non-null    str
 8   Fare         891 non-null    float64
 9   Cabin        204 non-null    str
 10  Embarked     889 non-null    str
 11  Survived     891 non-null    int64
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [13]:
df.drop(["Ticket"],axis=1,inplace=True)

In [15]:
df.head(2)

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1

In [27]:
target = df.Survived
inputs = df.drop("Survived",axis=1)

In [29]:
dummies=pd.get_dummies(inputs.Sex,drop_first=True)

In [19]:
dummies.head(2)

    male
0   True
1  False

In [30]:
inputs["Sex"] = dummies

In [31]:
inputs.head(2)

   Pclass    Sex   Age     Fare
0       3   True  22.0   7.2500
1       1  False  38.0  71.2833

In [38]:
inputs.columns[inputs.isnull().any()].tolist()

['Age']

In [46]:
inputs.Age.isnull().tolist()

[False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False]

In [48]:
inputs.Age=inputs.Age.fillna(inputs.Age.mean())

In [49]:
inputs.columns[inputs.isnull().any()].tolist()

[]

In [60]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(inputs,target,test_size=0.2)

In [61]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train,y_train)

GaussianNB()

In [62]:
gnb.score(X_test,y_test)

0.7821229050279329

In [63]:
gnb.predict_proba(X_test)

array([[9.34877864e-01, 6.51221362e-02],
       [9.65884153e-01, 3.41158465e-02],
       [9.68648554e-01, 3.13514459e-02],
       [8.89790207e-01, 1.10209793e-01],
       [4.38250389e-01, 5.61749611e-01],
       [7.86572161e-01, 2.13427839e-01],
       [9.34763645e-01, 6.52363549e-02],
       [9.63867658e-01, 3.61323418e-02],
       [1.92139884e-04, 9.99807860e-01],
       [7.10921726e-01, 2.89078274e-01],
       [9.68014567e-01, 3.19854326e-02],
       [1.91209525e-12, 1.00000000e+00],
       [3.04722880e-01, 6.95277120e-01],
       [9.60908748e-02, 9.03909125e-01],
       [9.24639577e-02, 9.07536042e-01],
       [9.68434662e-01, 3.15653375e-02],
       [2.49131225e-02, 9.75086877e-01],
       [2.95234558e-01, 7.04765442e-01],
       [3.34514530e-01, 6.65485470e-01],
       [9.33523298e-01, 6.64767024e-02],
       [4.88813687e-01, 5.11186313e-01],
       [6.77454470e-01, 3.22545530e-01],
       [9.67828845e-01, 3.21711548e-02],
       [2.71018943e-01, 7.28981057e-01],
       [6.55744757e-01, 3.44255243e-01],
       [9.65646233e-01, 3.43537673e-02],
       [5.46880806e-02, 9.45311919e-01],
       [9.33797445e-01, 6.62025545e-02],
       [9.34622807e-01, 6.53771933e-02],
       [9.68014567e-01, 3.19854326e-02],
       [2.70688915e-01, 7.29311085e-01],
       [6.07789462e-04, 9.99392211e-01],
       [9.67927137e-01, 3.20728628e-02],
       [4.20802444e-01, 5.79197556e-01],
       [9.67849709e-01, 3.21502906e-02],
       [9.68014567e-01, 3.19854326e-02],
       [9.68000262e-01, 3.19997377e-02],
       [3.23546823e-01, 6.76453177e-01],
       [8.79425313e-01, 1.20574687e-01],
       [3.38837693e-01, 6.61162307e-01],
       [9.68014567e-01, 3.19854326e-02],
       [7.57159578e-02, 9.24284042e-01],
       [4.83891952e-01, 5.16108048e-01],
       [9.60391781e-01, 3.96082195e-02],
       [8.81228331e-01, 1.18771669e-01],
       [9.64357256e-01, 3.56427442e-02],
       [9.29780914e-01, 7.02190862e-02],
       [4.73039449e-01, 5.26960551e-01],
       [8.89790207e-01, 1.10209793e-01],
       [3.03870432e-01, 6.96129568e-01],
       [7.50367967e-01, 2.49632033e-01],
       [4.60081903e-01, 5.39918097e-01],
       [3.27827578e-01, 6.72172422e-01],
       [9.68807541e-01, 3.11924593e-02],
       [3.03694694e-01, 6.96305306e-01],
       [9.68047181e-01, 3.19528194e-02],
       [9.15027439e-01, 8.49725607e-02],
       [9.34970331e-01, 6.50296692e-02],
       [7.20506817e-01, 2.79493183e-01],
       [9.68521228e-01, 3.14787720e-02],
       [9.66358132e-01, 3.36418683e-02],
       [4.78493624e-01, 5.21506376e-01],
       [4.83513416e-01, 5.16486584e-01],
       [7.91131748e-08, 9.99999921e-01],
       [7.04866740e-01, 2.95133260e-01],
       [4.83374915e-01, 5.16625085e-01],
       [9.65019470e-01, 3.49805303e-02],
       [9.67864409e-01, 3.21355914e-02],
       [9.64820008e-01, 3.51799915e-02],
       [9.36555720e-01, 6.34442797e-02],
       [1.31178273e-05, 9.99986882e-01],
       [9.68047181e-01, 3.19528194e-02],
       [9.68047181e-01, 3.19528194e-02],
       [3.03901028e-01, 6.96098972e-01],
       [9.66453125e-01, 3.35468750e-02],
       [2.55495488e-01, 7.44504512e-01],
       [9.67575759e-01, 3.24242409e-02],
       [9.30777819e-01, 6.92221806e-02],
       [6.64060904e-01, 3.35939096e-01],
       [9.67983078e-01, 3.20169218e-02],
       [7.58607607e-01, 2.41392393e-01],
       [6.02806711e-02, 9.39719329e-01],
       [7.79811367e-01, 2.20188633e-01],
       [4.89747901e-01, 5.10252099e-01],
       [9.67670196e-01, 3.23298038e-02],
       [9.65527540e-01, 3.44724602e-02],
       [4.86874313e-01, 5.13125687e-01],
       [9.23926655e-01, 7.60733450e-02],
       [9.67587101e-01, 3.24128995e-02],
       [1.73216298e-02, 9.82678370e-01],
       [9.52594429e-01, 4.74055711e-02],
       [7.86743333e-01, 2.13256667e-01],
       [9.66764367e-01, 3.32356334e-02],
       [9.67076166e-01, 3.29238343e-02],
       [4.21264654e-02, 9.57873535e-01],
       [9.68213028e-01, 3.17869719e-02],
       [9.67886956e-01, 3.21130442e-02],
       [9.68216897e-01, 3.17831032e-02],
       [1.47413876e-02, 9.85258612e-01],
       [9.67252712e-01, 3.27472884e-02],
       [9.61476199e-01, 3.85238006e-02],
       [8.80592978e-02, 9.11940702e-01],
       [7.33942266e-01, 2.66057734e-01],
       [9.64794313e-01, 3.52056870e-02],
       [9.34640435e-01, 6.53595653e-02],
       [9.23155648e-01, 7.68443524e-02],
       [4.52218935e-01, 5.47781065e-01],
       [9.68157802e-01, 3.18421984e-02],
       [6.37903719e-14, 1.00000000e+00],
       [2.77284256e-01, 7.22715744e-01],
       [9.67870248e-01, 3.21297521e-02],
       [9.62126107e-01, 3.78738925e-02],
       [9.09002856e-01, 9.09971440e-02],
       [9.67728726e-01, 3.22712743e-02],
       [2.95402656e-01, 7.04597344e-01],
       [2.83802265e-01, 7.16197735e-01],
       [9.63983878e-01, 3.60161220e-02],
       [1.79530363e-03, 9.98204696e-01],
       [6.13964324e-02, 9.38603568e-01],
       [9.27829209e-01, 7.21707907e-02],
       [1.57334191e-04, 9.99842666e-01],
       [2.07879560e-01, 7.92120440e-01],
       [7.75500446e-01, 2.24499554e-01],
       [3.45186940e-01, 6.54813060e-01],
       [9.34763645e-01, 6.52363549e-02],
       [2.64751027e-01, 7.35248973e-01],
       [1.33553286e-02, 9.86644671e-01],
       [9.47265548e-01, 5.27344521e-02],
       [9.66767174e-01, 3.32328263e-02],
       [9.64328160e-01, 3.56718403e-02],
       [7.70684177e-01, 2.29315823e-01],
       [1.18733386e-01, 8.81266614e-01],
       [9.66767174e-01, 3.32328263e-02],
       [7.83683556e-01, 2.16316444e-01],
       [9.67828014e-01, 3.21719865e-02],
       [9.67433379e-01, 3.25666209e-02],
       [9.34799420e-01, 6.52005803e-02],
       [4.84038869e-01, 5.15961131e-01],
       [9.34964159e-01, 6.50358413e-02],
       [9.68256965e-01, 3.17430353e-02],
       [9.67895979e-01, 3.21040213e-02],
       [4.83600114e-01, 5.16399886e-01],
       [9.31926552e-01, 6.80734482e-02],
       [4.84560496e-01, 5.15439504e-01],
       [9.67978534e-01, 3.20214659e-02],
       [1.42657659e-02, 9.85734234e-01],
       [4.23894400e-01, 5.76105600e-01],
       [9.68807786e-01, 3.11922138e-02],
       [9.62372316e-01, 3.76276845e-02],
       [9.66885938e-01, 3.31140619e-02],
       [9.60726703e-01, 3.92732968e-02],
       [4.85780627e-01, 5.14219373e-01],
       [9.32457053e-01, 6.75429469e-02],
       [9.65240321e-01, 3.47596788e-02],
       [6.06189379e-01, 3.93810621e-01],
       [9.65544957e-01, 3.44550427e-02],
       [7.31834489e-02, 9.26816551e-01],
       [4.64004462e-01, 5.35995538e-01],
       [2.65868455e-01, 7.34131545e-01],
       [5.52511002e-01, 4.47488998e-01],
       [7.74070600e-01, 2.25929400e-01],
       [4.69812558e-01, 5.30187442e-01],
       [4.45752393e-01, 5.54247607e-01],
       [3.20334590e-02, 9.67966541e-01],
       [9.42641615e-01, 5.73583845e-02],
       [9.61060670e-01, 3.89393300e-02],
       [9.08923367e-01, 9.10766332e-02],
       [4.53851092e-01, 5.46148908e-01],
       [9.61080924e-01, 3.89190761e-02],
       [2.44917403e-01, 7.55082597e-01],
       [9.67894194e-01, 3.21058060e-02],
       [4.81333532e-01, 5.18666468e-01],
       [1.86044035e-05, 9.99981396e-01],
       [7.62764899e-01, 2.37235101e-01],
       [9.67865391e-01, 3.21346090e-02],
       [8.68422845e-01, 1.31577155e-01],
       [9.67728726e-01, 3.22712743e-02],
       [9.68795384e-01, 3.12046162e-02],
       [9.64894087e-01, 3.51059127e-02]])